name: new_mns
description: ''
version: 0.0.1
author: siddhesh@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: newmns
  parentArtefactID: siddheshcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-19 11:24:09'
pipelines:
  pipelines/sample_testing:
    name: sample_testing
    description: ''
    author: siddhesh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-19 11:24:09'
    datasets:
      inputs:
      - datasets/category-description
      - datasets/customer-data
      - datasets/product-detail
      - datasets/product-order-data
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/category-description:
    name: category-description
    description: ''
    author: siddhesh@cloudaeon.net
    createdAt: '2024-03-19 11:26:10'
    mode: batch
    physicalDatasets:
      prophecy-demo-sid:
        fabricId: 10098
        datasetType: File
        description: ''
        author: siddhesh@cloudaeon.net
        createdAt: '2024-03-19 11:26:10'
  datasets/customer-data:
    name: customer-data
    description: ''
    author: siddhesh@cloudaeon.net
    createdAt: '2024-03-19 11:27:06'
    mode: batch
    physicalDatasets:
      prophecy-demo-sid:
        fabricId: 10098
        datasetType: File
        description: ''
        author: siddhesh@cloudaeon.net
        createdAt: '2024-03-19 11:27:06'
  datasets/product-detail:
    name: product-detail
    description: ''
    author: siddhesh@cloudaeon.net
    createdAt: '2024-03-19 11:28:12'
    mode: batch
    physicalDatasets:
      prophecy-demo-sid:
        fabricId: 10098
        datasetType: File
        description: ''
        author: siddhesh@cloudaeon.net
        createdAt: '2024-03-19 11:28:12'
  datasets/product-order-data:
    name: product-order-data
    description: ''
    author: siddhesh@cloudaeon.net
    createdAt: '2024-03-19 11:29:01'
    mode: batch
    physicalDatasets:
      prophecy-demo-sid:
        fabricId: 10098
        datasetType: File
        description: ''
        author: siddhesh@cloudaeon.net
        createdAt: '2024-03-19 11:29:01'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-19 11:24:09'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-19 11:23:33'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-19 11:23:33'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
